export type IColors =
  | "black"
  | "white"
  | "primary"
  | "primary-100"
  | "primary-200"
  | "primary-300"
  | "primary-400"
  | "primary-500" // Same as primary
  | "primary-600"
  | "primary-700"
  | "secondary"
  | "secondary-100"
  | "secondary-200"
  | "secondary-300"
  | "secondary-400"
  | "secondary-500" // Same as secondary
  | "secondary-600"
  | "secondary-700"
  | "success"
  | "sucess-dark"
  | "sucess-light"
  | "warning"
  | "warning-dark"
  | "warning-light"
  | "danger"
  | "danger-dark"
  | "danger-light"
  | "orange"
  | "amber"
  | "purple"
  | "gray"
  | "gray-50"
  | "gray-100"
  | "gray-200"
  | "gray-300"
  | "gray-400"
  | "gray-500"
  | "gray-600" // Same as gray
  | "gray-700"
  | "gray-800"
  | "gray-900"
  | "facebook"
  | "twitter"
  | "google";
